### ISSUE TITLE
Should link with pcre at build time (and not with dlopen)

### ISSUE THREAD

**Issue by rhertzog** [robertdavidgraham/heartleech#28]
While packaging your application for Kali linux, I noticed that heartleech needs "libpcre.so" to work properly. That file is only available if you have installed libpcre-dev and not if you have only libpcre3 (which provides libpcre.so.3). The reason why that file is needed is because you dlopen that library... but I see no reason why heartleech would need to dlopen() that library instead of using the symbols directly and linking against libpcre at build time (gcc -lpcre).

My request is thus to update heartleech to link against that library at bulld time to avoid the need of libpcre-dev at runtime and also to ensure we have proper dependencies generated automatically.

**Comment by robertdavidgraham** [comment]
Actually, heartleech doesn't **yet** use PCRE for anything. It doesn't use the library for anything other than to print the version number. I could comment out that line if you want.

I plan this for a future feature, to automatically search for patterns, like Cookies and passwords, but I haven't added that feature yet.

I'll fix this when I get around to using PCRE. I prefer to dynamically link at runtime, because I hate "dependency hell", taking hours to get a dependency installed for a feature in the product I don't even use. But, it's also pretty easy to make that a build option (load-time vs. run-time linking).

**Comment by rhertzog** [comment]
Huh, I hadn't realized that. I don't share your opinion about "dependency hell" but that's because I use a Linux distribution that has everything available and easily installable... so yes I'd definitely prefer to use build-time linking like it's the norm for most projects. Thank you!

There's no urgency though.

**Comment by robertdavidgraham** [comment]
I commented out the use of PCRE for the moment.
